backend = "glx";

vsync = false;
use-damage = true;            
unredir-if-possible = true;
unredir-if-possible-delay = 500;

xrender-sync-fence = false;

detect-transient = true;

shadow = false;
fading = false;

dithered-present = false;
