pcall(require, "luarocks.loader")
local gears = require("gears")
local awful = require("awful")
require("awful.autofocus")
local beautiful = require("beautiful")

require("error_handling.handle_startup_error")
require("error_handling.handle_runtime_error")

beautiful.init(gears.filesystem.get_configuration_dir() .. "theme.lua")
require("ui.layouts")
require("ui.bar")
local mouse_buttons = require("keybinds.mouse")
root.buttons(mouse_buttons)
local globalkeys = require("keybinds.globalkeys")
root.keys(globalkeys)
awful.rules.rules = require("rules")
require("signals.client")
