alias cdcode='cd /mnt/d/code'
alias ..='cd ../'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias up='sudo apt update; sudo apt upgrade; sudo apt-get autoremove; sudo apt-get clean'
alias ealias='vim ~/.bash_aliases'
alias startrdp='sudo /etc/init.d/xrdp start; mstsc.exe /v:localhost:3390'
alias stoprdp=' sudo /etc/init.d/xrdp stop'
alias rbash='source ~/.bashrc'
alias ra='source ~/.bashrc'
alias rdpshow='showrdp'
alias rdpstart='startrdp'
alias rdpstop='stoprdp'
alias showrdp='mstsc.exe /v:localhost:3390'
alias startrdp='sudo /etc/init.d/xrdp start'
alias stoprdp='sudo /etc/init.d/xrdp stop'
alias gitsh="'/mnt/c/Program Files/Git/bin/bash.exe' -i -l"
alias explorer='explorer.exe .'
alias ll="ls -l --time-style=long-iso"
alias lsh="ls -A -I'*'"
alias pyenv="source .venv/bin/activate"
alias httpserv="sudo python3 -m http.server"
alias cmd="cmd.exe"
alias cdusr="cd /mnt/c/Users/avner/"
