#!/bin/bash
if [ $(hostname) = "eclipse" ]; then
    xrandr --output HDMI-0 --pos 0x0 --rotate left --output DP-0   --pos 1080x0 --rotate normal --primary
fi

picom &
dunst &
clipmenud &
lxpolkit &

systemctl --user import-environment DISPLAY XAUTHORITY DBUS_SESSION_BUS_ADDRESS
dbus-update-activation-environment --systemd DISPLAY XAUTHORITY DBUS_SESSION_BUS_ADDRESS

#slstatus &
#exec dwm
exec awesome
