#!/bin/sh
if [ "$environment" != "wsl" ]; then
        echo "This script is only supported on WSL."
        exit 1
fi


### ctrl+arrows
bindkey "\e[1;5C" forward-word
bindkey "\e[1;5D" backward-word
# urxvt
bindkey "\eOc" forward-word
bindkey "\eOd" backward-word

### ctrl+delete
bindkey "\e[3;5~" kill-word
# urxvt
bindkey "\e[3^" kill-word

### ctrl+backspace
bindkey '^H' backward-kill-word

### ctrl+shift+delete
bindkey "\e[3;6~" kill-line
bindkey "\e[3@" kill-line

# history
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

# arrows
bindkey "^[[C" forward-char
bindkey "^[[D" backward-char

alias netext="cd /mnt/d/code/magshiproject && git status"

# WSL X server
export DISPLAY=$(route.exe print | awk '/0.0.0.0/ {print $4; exit;}'):0.0 2> /dev/null

# WSL locations
if env | grep -q '^WINUSERNAME='; then
  export DOWNLOADS="/mnt/c/Users/$WINUSERNAME/Downloads"
  export WINUSER="/mnt/c/Users/$WINUSERNAME/"
fi
export CODE="/mnt/d/code"
export CDRIVE="/mnt/c"
export DDRIVE="/mnt/d"
export HDRIVE="/mnt/h"

# WSL aliases
alias cmdo='cmd.exe /c'
alias cmd="cmd.exe"
alias cmdpy='cd "$(pwd -P)" && cmd.exe /k "cd /d $(wslpath -w "$(pwd -P)") && call .venv\\Scripts\\activate.bat"'
alias xpl='explorer.exe .'
alias everything="/mnt/c/Program\ Files/Everything/Everything.exe"
alias gitsh="'/mnt/c/Program Files/Git/bin/bash.exe' -i -l"

alias todo="todo-txt"
