[general]
import = [
  "~/.cache/wal/colors-alacritty.toml",
]
live_config_reload = true
[scrolling]
history = 100000
[mouse]
hide_when_typing = true
[window]
padding = { x = 6, y = 3 }
[font]
size = 10.25
